apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
spec:
  ports:
  - name: http2
    nodePort: 32333
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort
